name: "Set Rancher environment variables"
runs:
  using: "composite"
  steps:
    - name: "Set Rancher environment variables"
      run: |
        echo "RANCHER_BEARER_TOKEN=${{ inputs.rancher_bearer_token }}" >> $GITHUB_ENV
        echo "RANCHER_CLUSTER_ID=${{ inputs.rancher_cluster_id }}" >> $GITHUB_ENV
        echo "RANCHER_PROJECT_ID=${{ inputs.rancher_project_id }}" >> $GITHUB_ENV
        echo "RANCHER_URL=${{ inputs.rancher_url }}" >> $GITHUB_ENV
        if [[ ${{ github.ref }} == refs/heads/staging ]]; then
          echo "RANCHER_NAMESPACE=${{ inputs.rancher_staging_namespace }}" >> $GITHUB_ENV
          echo "RANCHER_WORKLOADS=${{ inputs.rancher_staging_workloads }}" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == refs/heads/main ]]; then
          echo "RANCHER_NAMESPACE=${{ inputs.rancher_namespace }}" >> $GITHUB_ENV
          echo "RANCHER_WORKLOADS=${{ inputs.rancher_workloads }}" >> $GITHUB_ENV

        else
          echo Invalid ref.
          exit 1
        fi
      shell: bash
